# Copyright (c) 2022 Espresso Systems (espressosys.com)
# This file is part of the Espresso library.

name: Windows build

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.64"

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Check
        run: cargo check --workspace --all-targets
